version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - PORT=8080
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
