replicaCount: 1

image:
  repository: shambhand/devops-journey
  pullPolicy: Always #IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
